//! `protobuf` subcommand -- stdin/stdout protobuf <-> JSON conversion (D-02).
//!
//! Covers all three D-02 schemas: collection/v2 (`PageRequest`/`PageResponse`),
//! recently-played (the backend `RecentlyPlayed` wrapper), and rootlist
//! (`Response` and its full folder/playlist tree). `decode` reads raw
//! protobuf bytes from stdin and emits JSON on stdout; `encode` is
//! supported only for collection-v2 (the only schema with a request
//! message upstream) and reads JSON from stdin, emitting protobuf bytes on
//! stdout.
//!
//! Untrusted stdin is bounded (`MAX_STDIN_BYTES`) and decoded via the
//! generated types' safe `protobuf::Message` API -- no `unsafe`, no manual
//! varint/pointer math (RESEARCH.md T-74-08). Any parse failure returns an
//! `Err`; `main.rs` turns that into a single-line JSON error object on
//! stdout and a non-zero exit (RESEARCH.md T-74-07) -- this module never
//! panics or unwraps on data that came from stdin.

use anyhow::{bail, Context, Result};
use protobuf::{EnumOrUnknown, Message};
use serde_json::{json, Value};
use std::io::{Read, Write};

// Generated by build.rs (`protobuf_codegen::Codegen` `.pure()` path) from
// the vendored `proto/` schemas -- see build.rs for the exact input list.
mod protos {
    include!(concat!(env!("OUT_DIR"), "/protos/mod.rs"));
}

use protos::collection2v2;
use protos::playlist_folder_state;
use protos::playlist_permission;
use protos::playlist_playlist_state;
use protos::playlist_user_state;
use protos::protobuf_delta;
use protos::recently_played_backend;
use protos::rootlist_request;
use protos::{extension, image_group};

/// Reject stdin larger than this many bytes. A real collection/v2 page or
/// rootlist response is at most a few hundred KB; anything past a few MB on
/// stdin is either a caller bug or a DoS attempt (RESEARCH.md T-74-07).
const MAX_STDIN_BYTES: usize = 8 * 1024 * 1024;

/// Entry point wired from `main.rs`'s `Cmd::Protobuf` arm.
pub fn run(schema: &str, mode: &str) -> Result<()> {
    let input = read_stdin_bounded()?;
    match process(schema, mode, &input)? {
        Output::Json(v) => {
            println!("{v}");
            Ok(())
        }
        Output::Bytes(b) => write_stdout_bytes(&b),
    }
}

#[derive(Debug)]
enum Output {
    Json(Value),
    Bytes(Vec<u8>),
}

/// Pure dispatch -- no I/O -- so it is directly unit-testable.
fn process(schema: &str, mode: &str, input: &[u8]) -> Result<Output> {
    match (schema, mode) {
        ("collection-v2", "decode") => decode_collection_v2(input).map(Output::Json),
        ("collection-v2", "encode") => encode_collection_v2(input).map(Output::Bytes),
        ("recently-played", "decode") => decode_recently_played(input).map(Output::Json),
        ("recently-played", "encode") => decode_only_error("recently-played"),
        ("rootlist", "decode") => decode_rootlist(input).map(Output::Json),
        ("rootlist", "encode") => decode_only_error("rootlist"),
        (_, "decode") | (_, "encode") => bail!(
            "unknown schema '{schema}' -- supported schemas: collection-v2, recently-played, rootlist"
        ),
        (_, other) => bail!("unknown mode '{other}' -- supported modes: decode, encode"),
    }
}

fn decode_only_error(schema: &str) -> Result<Output> {
    bail!(
        "schema '{schema}' is decode-only -- the upstream protobuf schema \
         defines no request message to encode"
    )
}

// ---------------------------------------------------------------------
// stdin / stdout plumbing
// ---------------------------------------------------------------------

/// Read `r` fully into memory, refusing anything over [`MAX_STDIN_BYTES`].
/// Generic over `Read` so tests can feed a `Cursor` instead of real stdin.
fn read_bounded<R: Read>(mut r: R) -> Result<Vec<u8>> {
    let mut buf = Vec::new();
    r.by_ref()
        .take(MAX_STDIN_BYTES as u64 + 1)
        .read_to_end(&mut buf)
        .context("failed to read stdin")?;
    if buf.len() > MAX_STDIN_BYTES {
        bail!("input exceeds the {MAX_STDIN_BYTES}-byte limit");
    }
    Ok(buf)
}

fn read_stdin_bounded() -> Result<Vec<u8>> {
    read_bounded(std::io::stdin())
}

fn write_stdout_bytes(bytes: &[u8]) -> Result<()> {
    std::io::stdout()
        .write_all(bytes)
        .context("failed to write stdout")
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn enum_json<E: protobuf::Enum + std::fmt::Debug>(e: &EnumOrUnknown<E>) -> Value {
    match e.enum_value() {
        Ok(v) => json!(format!("{v:?}")),
        Err(unknown) => json!(unknown),
    }
}

// ---------------------------------------------------------------------
// collection/v2 -- PageRequest (encode) / PageResponse (decode)
// ---------------------------------------------------------------------

fn decode_collection_v2(input: &[u8]) -> Result<Value> {
    let msg = collection2v2::PageResponse::parse_from_bytes(input)
        .context("malformed collection-v2 PageResponse protobuf")?;
    Ok(page_response_to_json(&msg))
}

fn encode_collection_v2(input: &[u8]) -> Result<Vec<u8>> {
    let value: Value = serde_json::from_slice(input).context("malformed JSON on stdin")?;
    let req = json_to_page_request(&value);
    req.write_to_bytes()
        .context("failed to encode PageRequest")
}

fn page_response_to_json(msg: &collection2v2::PageResponse) -> Value {
    json!({
        "items": msg.items.iter().map(collection_item_to_json).collect::<Vec<_>>(),
        "next_page_token": msg.next_page_token,
        "sync_token": msg.sync_token,
    })
}

fn collection_item_to_json(item: &collection2v2::CollectionItem) -> Value {
    json!({
        "uri": item.uri,
        "added_at": item.added_at,
        "is_removed": item.is_removed,
        "context_uri": item.context_uri,
    })
}

fn json_to_page_request(v: &Value) -> collection2v2::PageRequest {
    let mut req = collection2v2::PageRequest::new();
    req.username = json_str(v, "username");
    req.set = json_str(v, "set");
    req.pagination_token = json_str(v, "pagination_token");
    req.limit = v.get("limit").and_then(Value::as_i64).unwrap_or(0) as i32;
    req
}

fn json_str(v: &Value, field: &str) -> String {
    v.get(field)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

// ---------------------------------------------------------------------
// recently-played -- backend RecentlyPlayed wrapper (decode-only)
// ---------------------------------------------------------------------

fn decode_recently_played(input: &[u8]) -> Result<Value> {
    let msg = recently_played_backend::RecentlyPlayed::parse_from_bytes(input)
        .context("malformed recently-played protobuf")?;
    Ok(recently_played_to_json(&msg))
}

fn recently_played_to_json(msg: &recently_played_backend::RecentlyPlayed) -> Value {
    json!({
        "contexts": msg.contexts.iter().map(context_to_json).collect::<Vec<_>>(),
        "offset": msg.offset,
        "total": msg.total,
    })
}

fn context_to_json(ctx: &recently_played_backend::Context) -> Value {
    json!({
        "uri": ctx.uri,
        "lastPlayedTime": ctx.lastPlayedTime,
    })
}

// ---------------------------------------------------------------------
// rootlist -- Response + full Folder/Item/Playlist tree (decode-only)
// ---------------------------------------------------------------------

fn decode_rootlist(input: &[u8]) -> Result<Value> {
    let msg = rootlist_request::Response::parse_from_bytes(input)
        .context("malformed rootlist Response protobuf")?;
    Ok(rootlist_response_to_json(&msg))
}

fn rootlist_response_to_json(msg: &rootlist_request::Response) -> Value {
    json!({
        "root": msg.root.as_ref().map(folder_to_json),
        "unfiltered_length": msg.unfiltered_length,
        "unranged_length": msg.unranged_length,
        "is_loading_contents": msg.is_loading_contents,
    })
}

fn folder_to_json(folder: &rootlist_request::Folder) -> Value {
    json!({
        "item": folder.item.iter().map(item_to_json).collect::<Vec<_>>(),
        "folder_metadata": folder.folder_metadata.as_ref().map(folder_metadata_to_json),
        "row_id": folder.row_id,
        "add_time": folder.add_time,
        "group_label": folder.group_label,
    })
}

fn item_to_json(item: &rootlist_request::Item) -> Value {
    json!({
        "header_field": item.header_field,
        "folder": item.folder.as_ref().map(folder_to_json),
        "playlist": item.playlist.as_ref().map(playlist_to_json),
        "delta": item.delta.as_ref().map(delta_to_json),
    })
}

fn playlist_to_json(playlist: &rootlist_request::Playlist) -> Value {
    json!({
        "row_id": playlist.row_id,
        "playlist_metadata": playlist.playlist_metadata.as_ref().map(playlist_metadata_to_json),
        "playlist_offline_state": playlist.playlist_offline_state.as_ref().map(playlist_offline_state_to_json),
        "add_time": playlist.add_time,
        "is_on_demand_in_free": playlist.is_on_demand_in_free,
        "group_label": playlist.group_label,
        "capabilities": playlist.capabilities.as_ref().map(capabilities_to_json),
    })
}

fn folder_metadata_to_json(m: &playlist_folder_state::FolderMetadata) -> Value {
    json!({
        "id": m.id,
        "name": m.name,
        "num_folders": m.num_folders,
        "num_playlists": m.num_playlists,
        "num_recursive_folders": m.num_recursive_folders,
        "num_recursive_playlists": m.num_recursive_playlists,
        "link": m.link,
    })
}

fn playlist_metadata_to_json(m: &playlist_playlist_state::PlaylistMetadata) -> Value {
    json!({
        "link": m.link,
        "name": m.name,
        "owner": m.owner.as_ref().map(user_to_json),
        "owned_by_self": m.owned_by_self,
        "collaborative": m.collaborative,
        "total_length": m.total_length,
        "description": m.description,
        "pictures": m.pictures.as_ref().map(image_group_to_json),
        "followed": m.followed,
        "published": m.published,
        "browsable_offline": m.browsable_offline,
        "description_from_annotate": m.description_from_annotate,
        "picture_from_annotate": m.picture_from_annotate,
        "format_list_type": m.format_list_type,
        "format_list_attributes": m.format_list_attributes.iter().map(format_list_attribute_to_json).collect::<Vec<_>>(),
        "can_report_annotation_abuse": m.can_report_annotation_abuse,
        "is_loaded": m.is_loaded,
        "allows": m.allows.as_ref().map(allows_to_json),
        "load_state": m.load_state,
        "made_for": m.made_for.as_ref().map(user_to_json),
        "extension": m.extension.iter().map(extension_to_json).collect::<Vec<_>>(),
        "length_ignoring_text_filter": m.length_ignoring_text_filter,
        "ai_curation_reference_id": m.ai_curation_reference_id,
    })
}

fn playlist_offline_state_to_json(m: &playlist_playlist_state::PlaylistOfflineState) -> Value {
    json!({
        "offline": m.offline,
        "sync_progress": m.sync_progress,
    })
}

fn user_to_json(u: &playlist_user_state::User) -> Value {
    json!({
        "link": u.link,
        "username": u.username,
        "display_name": u.display_name,
        "image_uri": u.image_uri,
        "thumbnail_uri": u.thumbnail_uri,
        "color": u.color,
    })
}

fn allows_to_json(a: &playlist_playlist_state::Allows) -> Value {
    json!({
        "can_insert": a.can_insert,
        "can_remove": a.can_remove,
    })
}

fn format_list_attribute_to_json(a: &playlist_playlist_state::FormatListAttribute) -> Value {
    json!({
        "key": a.key,
        "value": a.value,
    })
}

fn image_group_to_json(g: &image_group::ImageGroup) -> Value {
    json!({
        "standard_link": g.standard_link,
        "small_link": g.small_link,
        "large_link": g.large_link,
        "xlarge_link": g.xlarge_link,
    })
}

fn extension_to_json(e: &extension::Extension) -> Value {
    json!({
        "extension_kind": e.extension_kind.as_ref().map(enum_json),
        // Opaque payload -- hex-encoded rather than pulling in a base64 dep
        // for a field Phase 75 does not need to interpret.
        "data": e.data.as_deref().map(hex_encode),
    })
}

fn capabilities_to_json(c: &playlist_permission::Capabilities) -> Value {
    json!({
        "can_view": c.can_view,
        "can_administrate_permissions": c.can_administrate_permissions,
        "grantable_level": c.grantable_level.iter().map(enum_json).collect::<Vec<_>>(),
        "can_edit_metadata": c.can_edit_metadata,
        "can_edit_items": c.can_edit_items,
        "can_cancel_membership": c.can_cancel_membership,
        "grantable_levels": c.grantable_levels.as_ref().map(grantable_levels_to_json),
        "list_attribute_capabilities": c.list_attribute_capabilities.as_ref().map(list_attribute_capabilities_to_json),
    })
}

fn grantable_levels_to_json(g: &playlist_permission::GrantableLevels) -> Value {
    json!({
        "base": g.base.iter().map(enum_json).collect::<Vec<_>>(),
        "member": g.member.iter().map(enum_json).collect::<Vec<_>>(),
    })
}

fn list_attribute_capabilities_to_json(l: &playlist_permission::ListAttributeCapabilities) -> Value {
    json!({
        "name": l.name.as_ref().map(attribute_capabilities_to_json),
        "description": l.description.as_ref().map(attribute_capabilities_to_json),
        "picture": l.picture.as_ref().map(attribute_capabilities_to_json),
        "collaborative": l.collaborative.as_ref().map(attribute_capabilities_to_json),
        "deleted_by_owner": l.deleted_by_owner.as_ref().map(attribute_capabilities_to_json),
        "ai_curation_reference_id": l.ai_curation_reference_id.as_ref().map(attribute_capabilities_to_json),
    })
}

fn attribute_capabilities_to_json(a: &playlist_permission::AttributeCapabilities) -> Value {
    json!({ "can_edit": a.can_edit })
}

fn delta_to_json(d: &protobuf_delta::Delta) -> Value {
    json!({
        "type": d.type_.as_ref().map(enum_json),
        "index": d.index,
        "length": d.length,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use protobuf::MessageField;

    #[test]
    fn collection_v2_decode_roundtrip() {
        let mut item = collection2v2::CollectionItem::new();
        item.uri = "spotify:track:abc".to_string();
        item.added_at = 1_700_000_000;
        item.is_removed = true;

        let mut resp = collection2v2::PageResponse::new();
        resp.items.push(item);
        resp.next_page_token = "next".to_string();
        let bytes = resp.write_to_bytes().expect("encode fixture");

        let json = decode_collection_v2(&bytes).expect("decode");
        assert_eq!(json["items"][0]["uri"], "spotify:track:abc");
        assert_eq!(json["items"][0]["added_at"], 1_700_000_000);
        assert_eq!(json["items"][0]["is_removed"], true);
        assert_eq!(json["next_page_token"], "next");
    }

    #[test]
    fn collection_v2_encode_roundtrip() {
        let request_json = json!({
            "username": "alice",
            "set": "starred",
            "pagination_token": "tok",
            "limit": 50,
        });
        let input = serde_json::to_vec(&request_json).expect("serialize fixture");

        let encoded = encode_collection_v2(&input).expect("encode");
        let parsed =
            collection2v2::PageRequest::parse_from_bytes(&encoded).expect("parse back");

        assert_eq!(parsed.username, "alice");
        assert_eq!(parsed.set, "starred");
        assert_eq!(parsed.pagination_token, "tok");
        assert_eq!(parsed.limit, 50);
    }

    #[test]
    fn recently_played_decode_roundtrip() {
        let mut ctx = recently_played_backend::Context::new();
        ctx.uri = Some("spotify:track:xyz".to_string());
        ctx.lastPlayedTime = Some(123_456_789);

        let mut msg = recently_played_backend::RecentlyPlayed::new();
        msg.contexts.push(ctx);
        msg.offset = Some(0);
        msg.total = Some(1);
        let bytes = msg.write_to_bytes().expect("encode fixture");

        let json = decode_recently_played(&bytes).expect("decode");
        assert_eq!(json["contexts"][0]["uri"], "spotify:track:xyz");
        assert_eq!(json["contexts"][0]["lastPlayedTime"], 123_456_789);
        assert_eq!(json["total"], 1);
    }

    #[test]
    fn rootlist_decode_roundtrip() {
        let mut playlist = rootlist_request::Playlist::new();
        playlist.row_id = Some("row-1".to_string());

        let mut item = rootlist_request::Item::new();
        item.playlist = MessageField::some(playlist);

        let mut folder = rootlist_request::Folder::new();
        folder.item.push(item);
        folder.row_id = Some("folder-root".to_string());

        let mut resp = rootlist_request::Response::new();
        resp.root = MessageField::some(folder);
        let bytes = resp.write_to_bytes().expect("encode fixture");

        let json = decode_rootlist(&bytes).expect("decode");
        assert_eq!(json["root"]["row_id"], "folder-root");
        assert_eq!(json["root"]["item"][0]["playlist"]["row_id"], "row-1");
    }

    #[test]
    fn recently_played_encode_is_decode_only() {
        let err = process("recently-played", "encode", b"{}").unwrap_err();
        assert!(err.to_string().contains("decode-only"));
    }

    #[test]
    fn rootlist_encode_is_decode_only() {
        let err = process("rootlist", "encode", b"{}").unwrap_err();
        assert!(err.to_string().contains("decode-only"));
    }

    #[test]
    fn malformed_protobuf_returns_error_not_panic() {
        let bogus = vec![0xFF, 0x00, 0xAB, 0xCD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF];
        let result = decode_collection_v2(&bogus);
        assert!(result.is_err());
    }

    #[test]
    fn malformed_json_returns_error_not_panic() {
        let result = encode_collection_v2(b"{not valid json");
        assert!(result.is_err());
    }

    #[test]
    fn oversized_input_is_rejected() {
        let big = vec![0u8; MAX_STDIN_BYTES + 1];
        let result = read_bounded(std::io::Cursor::new(big));
        assert!(result.is_err());
    }

    #[test]
    fn unknown_schema_lists_supported_schemas() {
        let err = process("bogus-schema", "decode", b"").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("collection-v2"));
        assert!(msg.contains("recently-played"));
        assert!(msg.contains("rootlist"));
    }
}
